#line 2 "fsml.yy.cc"

#line 4 "fsml.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer FSML_create_buffer
#define yy_delete_buffer FSML_delete_buffer
#define yy_flex_debug FSML_flex_debug
#define yy_init_buffer FSML_init_buffer
#define yy_flush_buffer FSML_flush_buffer
#define yy_load_buffer_state FSML_load_buffer_state
#define yy_switch_to_buffer FSML_switch_to_buffer
#define yyin FSMLin
#define yyleng FSMLleng
#define yylex FSMLlex
#define yylineno FSMLlineno
#define yyout FSMLout
#define yyrestart FSMLrestart
#define yytext FSMLtext
#define yywrap FSMLwrap
#define yyalloc FSMLalloc
#define yyrealloc FSMLrealloc
#define yyfree FSMLfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE FSMLrestart(FSMLin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t FSMLleng;

extern FILE *FSMLin, *FSMLout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up FSMLtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up FSMLtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via FSMLrestart()), so that the user can continue scanning by
	 * just pointing FSMLin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when FSMLtext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t FSMLleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow FSMLwrap()'s to do buffer switches
 * instead of setting up a fresh FSMLin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void FSMLrestart (FILE *input_file  );
void FSML_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE FSML_create_buffer (FILE *file,int size  );
void FSML_delete_buffer (YY_BUFFER_STATE b  );
void FSML_flush_buffer (YY_BUFFER_STATE b  );
void FSMLpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void FSMLpop_buffer_state (void );

static void FSMLensure_buffer_stack (void );
static void FSML_load_buffer_state (void );
static void FSML_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER FSML_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE FSML_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE FSML_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE FSML_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *FSMLalloc (yy_size_t  );
void *FSMLrealloc (void *,yy_size_t  );
void FSMLfree (void *  );

#define yy_new_buffer FSML_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        FSMLensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            FSML_create_buffer(FSMLin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        FSMLensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            FSML_create_buffer(FSMLin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define FSMLwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *FSMLin = (FILE *) 0, *FSMLout = (FILE *) 0;

typedef int yy_state_type;

extern int FSMLlineno;

int FSMLlineno = 1;

extern char *FSMLtext;
#define yytext_ptr FSMLtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up FSMLtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	FSMLleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[201] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   58,   58,   66,   66,
       75,   73,   72,   71,   52,   53,   56,   54,   73,   55,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   50,   51,    4,    8,    9,
       73,   27,   14,   27,   39,   48,   32,   37,   36,   43,
       63,   64,   63,    5,    6,   40,   41,   58,   60,   59,
       66,   68,   67,   72,   65,   70,   49,   49,   49,   49,
       49,   49,   49,   49,   44,   49,   49,   38,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,    0,    0,
       27,   27,   57,   62,   58,   59,   59,   61,   66,   67,
       67,   69,   70,   49,   49,   49,   34,   49,   35,   49,
        7,   49,   18,   49,   46,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   10,   49,   28,   29,
       62,   16,    1,   49,   26,   49,   49,   19,   49,   49,
       49,   49,   49,   49,   49,   49,   49,    2,   49,   49,
       49,   15,   49,   20,   11,   49,   49,   33,   45,   17,
       49,   47,   31,   49,   49,   13,   24,   49,   30,   21,
       12,    3,   22,   25,   49,   49,   42,   49,   23,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    4,    5,
        6,    7,    1,    8,    1,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,    1,
       13,    1,    1,    1,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       15,    1,   16,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   14,   14,   27,   28,   29,
       30,   31,   14,   32,   33,   34,   35,   36,   14,   14,
       37,   14,   38,    1,   39,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[40] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        4,    1,    1,    4,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1
    } ;

static yyconst flex_int16_t yy_base[212] =
    {   0,
        0,    0,  216,  215,  214,  213,  212,  211,    2,    4,
       40,   42,   36,   38,   50,   51,  232,  231,  240,  239,
       46,   48,   58,   61,   64,   70,   74,   75,   76,   83,
      244,  255,  241,  255,  255,  255,  255,  255,   77,  255,
        0,  217,   63,   62,   65,  211,  211,  209,   66,  216,
      215,   77,  210,  206,   86,  255,  255,  255,  255,  255,
        0,   96,  255,  223,  255,  255,  255,  255,  255,  255,
      255,  255,   99,  255,  255,  255,  255,    0,  255,  103,
        0,  255,  105,  231,  255,    0,    0,  214,  211,  195,
       87,  197,  198,  199,    0,   83,  197,    0,  191,  192,

       85,  193,  198,  102,  193,   95,  188,  193,  214,  206,
      114,  205,  255,    0,    0,  117,  123,  255,    0,  125,
      129,  255,    0,  183,  187,  194,    0,  184,    0,  193,
        0,  175,    0,  185,  177,  181,  184,  173,  172,  174,
      106,  167,  179,  170,  173,  172,    0,  176,  255,  132,
        0,    0,    0,  169,    0,  161,  160,    0,  158,  162,
      157,  153,  155,  166,  153,  164,  165,  112,  153,  154,
      147,    0,  149,    0,    0,  136,  145,    0,    0,    0,
      142,    0,    0,  128,  123,    0,    0,  108,    0,    0,
        0,    0,    0,    0,   97,  104,    0,   51,    0,  255,

      144,  148,  152,   41,  156,  160,  164,  168,  172,  176,
      180
    } ;

static yyconst flex_int16_t yy_def[212] =
    {   0,
      200,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  201,  201,  201,  201,  202,  202,  203,  203,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  200,  200,  200,  200,  200,
      205,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  206,  200,  207,
      208,  200,  209,  200,  200,  210,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  200,  200,
      200,  200,  200,  211,  206,  207,  207,  200,  208,  209,
      209,  200,  210,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  200,  200,
      211,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,    0,

      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200
    } ;

static yyconst flex_int16_t yy_nxt[295] =
    {   0,
       32,   33,   34,   32,   35,   36,   37,   38,   32,   39,
       32,   32,   40,   41,   32,   32,   32,   41,   41,   42,
       43,   44,   45,   46,   41,   47,   48,   41,   41,   49,
       50,   51,   52,   53,   54,   55,   41,   56,   57,   59,
       60,   59,   60,   61,   87,   61,   64,   63,   64,   63,
       62,   63,   62,   63,   65,   65,   64,   66,   64,   66,
       72,   66,   66,   72,   67,   67,   72,   73,   76,   77,
       73,  199,   72,   73,   76,   77,   79,   79,   82,   73,
       80,   80,   83,   85,   89,   82,   86,   68,   68,   83,
       91,   93,   90,   92,   98,   74,   75,   94,   74,   75,

       99,  102,  103,  107,  110,  113,  111,  127,  114,  117,
      104,  121,  118,  132,  122,  108,  133,  137,  138,  141,
      144,  128,  110,  200,  111,  198,  200,  145,  146,  117,
      197,  200,  118,  142,  200,  121,  196,  165,  122,  166,
      110,  185,  150,  186,   71,   71,   71,   71,   78,   78,
       78,   78,   81,   81,   81,   81,  109,  195,  109,  109,
      115,  194,  193,  115,  116,  192,  116,  116,  119,  191,
      190,  119,  120,  189,  120,  120,  123,  188,  123,  123,
      151,  187,  151,  151,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,

      168,  167,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  112,  150,  149,  148,  147,
      143,  140,  139,  136,  135,  134,  131,  130,  129,  126,
      125,  124,   84,  112,  106,  105,  101,  100,   97,   96,
       95,   88,   84,  200,   70,   70,   69,   69,   58,   58,
       58,   58,   58,   58,   31,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200

    } ;

static yyconst flex_int16_t yy_chk[295] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
        9,   10,   10,   11,  204,   12,   13,   13,   14,   14,
       11,   11,   12,   12,   15,   16,   21,   21,   22,   22,
       23,   15,   16,   24,   15,   16,   25,   23,   25,   25,
       24,  198,   26,   25,   26,   26,   27,   28,   29,   26,
       27,   28,   29,   39,   43,   30,   39,   15,   16,   30,
       44,   45,   43,   44,   49,   23,   23,   45,   24,   24,

       49,   52,   52,   55,   62,   73,   62,   91,   73,   80,
       52,   83,   80,   96,   83,   55,   96,  101,  101,  104,
      106,   91,  111,  116,  111,  196,  116,  106,  106,  117,
      195,  120,  117,  104,  120,  121,  188,  141,  121,  141,
      150,  168,  150,  168,  201,  201,  201,  201,  202,  202,
      202,  202,  203,  203,  203,  203,  205,  185,  205,  205,
      206,  184,  181,  206,  207,  177,  207,  207,  208,  176,
      173,  208,  209,  171,  209,  209,  210,  170,  210,  210,
      211,  169,  211,  211,  167,  166,  165,  164,  163,  162,
      161,  160,  159,  157,  156,  154,  148,  146,  145,  144,

      143,  142,  140,  139,  138,  137,  136,  135,  134,  132,
      130,  128,  126,  125,  124,  112,  110,  109,  108,  107,
      105,  103,  102,  100,   99,   97,   94,   93,   92,   90,
       89,   88,   84,   64,   54,   53,   51,   50,   48,   47,
       46,   42,   33,   31,   20,   19,   18,   17,    8,    7,
        6,    5,    4,    3,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int FSML_flex_debug;
int FSML_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *FSMLtext;
#line 1 "fsml.lex"
/**
 *       @file  fsml.lexpp
 *      @brief  The scanner definition for the FSML (Finite State Machine Language)
 *
 *
 *     @author  Niccolo` Battezzati, niccolo.battezzati@argotecgroup.com
 *
 *   @internal
 *     Created  20/09/2020
 *     Company  Argotec S.r.l
 *   Copyright  Copyright (c) 2020, Argotec S.r.l
 *
 * This source code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This source code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser Public License for more details.

 * You should have received a copy of the GNU Lesser Public License
 * along with this source code.  If not, see <http://www.gnu.org/licenses/>.
 * =====================================================================================
 */
#line 31 "fsml.lex"
#include <stdio.h>
#include <string>
#include <errno.h>


#include "FSMLDriver.h"
#include "fsml.hh" 
#include "fsml_inner.h"

#ifdef DEBUG
#define log(...) printf(__VA_ARGS__)
#else
#define log(...)
#endif

#define yyterminate()	return token::END_OF_FILE

#define FSMLlval 		yylval 


typedef FSML::FSMLParser::token token;


int line = 1;			/* line counter */
int cb_cnt = 0;			/* counter for curly braces */
int b_cnt = 0;			/* counter for round brackets */

std::string tmp_str;	/* used to collect characters scanned by different rules in a unique token */

 

#line 665 "fsml.yy.cc"

#define INITIAL 0
#define DECL 1
#define TIME 2
#define PERIOD 3
#define FSM 4
#define VAR 5
#define TIMER 6
#define STATE 7
#define STATE_TYPE 8
#define TIMEOUT 9
#define UNTIL 10
#define C_CODE 11
#define C_CONDITION 12
#define C_COMMENT 13
#define FSML_COMMENT 14

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int FSMLlex_destroy (void );

int FSMLget_debug (void );

void FSMLset_debug (int debug_flag  );

YY_EXTRA_TYPE FSMLget_extra (void );

void FSMLset_extra (YY_EXTRA_TYPE user_defined  );

FILE *FSMLget_in (void );

void FSMLset_in  (FILE * in_str  );

FILE *FSMLget_out (void );

void FSMLset_out  (FILE * out_str  );

yy_size_t FSMLget_leng (void );

char *FSMLget_text (void );

int FSMLget_lineno (void );

void FSMLset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int FSMLwrap (void );
#else
extern int FSMLwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( FSMLtext, FSMLleng, 1, FSMLout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( FSMLin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( FSMLin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, FSMLin))==0 && ferror(FSMLin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(FSMLin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int FSMLlex (void);

#define YY_DECL int FSMLlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after FSMLtext and FSMLleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 74 "fsml.lex"



#line 873 "fsml.yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! FSMLin )
			FSMLin = stdin;

		if ( ! FSMLout )
			FSMLout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			FSMLensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				FSML_create_buffer(FSMLin,YY_BUF_SIZE );
		}

		FSML_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of FSMLtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 201 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 200 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 "fsml.lex"
{
				log("found: DECL\n");
				yy_push_state(DECL);
				return token::DECL_KEY;
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 83 "fsml.lex"
{
				log("found: TIME\n");
				yy_push_state(TIME);
				return token::TIME_KEY;
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "fsml.lex"
{
				log("found: PERIOD\n");
				yy_push_state(PERIOD);
				return token::PERIOD_KEY;
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 95 "fsml.lex"
{
				log("Beginning C-CODE\n");
				tmp_str += std::string(FSMLtext);
				yy_push_state(C_CODE);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 101 "fsml.lex"
{
				tmp_str += std::string(FSMLtext);
				cb_cnt++;
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 106 "fsml.lex"
{
				tmp_str += std::string(FSMLtext);
				cb_cnt--;
				if (cb_cnt < 0) {
					log("found: C_CODE\n");
					cb_cnt = 0;
					switch (yy_top_state()) {
						case DECL:
						case TIME:
						case PERIOD:
							yy_pop_state();
						break;

						default: break;
					}
					yy_pop_state();
					FSMLlval->emplace<std::string>(tmp_str); 
					tmp_str.clear();
					return token::C_CODE_BLOCK;
				}
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 128 "fsml.lex"
{
				log("found: FSM\n");
				yy_push_state(FSM);
				return token::FSM_KEY;
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 134 "fsml.lex"
{
				log("found: LCB\n");
				return token::LCB;
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 140 "fsml.lex"
{
				log("found: RCB\n");
				yy_pop_state();
				return token::RCB;
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 146 "fsml.lex"
{
				log("found: VAR\n");
				yy_push_state(VAR);
				return token::VAR_KEY;
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 152 "fsml.lex"
{
				log("found: INPUT\n");
				yy_push_state(VAR);
				return token::INPUT_KEY;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 158 "fsml.lex"
{
				log("found: OUTPUT\n");
				yy_push_state(VAR);
				return token::OUTPUT_KEY;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 164 "fsml.lex"
{
				log("found: TIMER\n");
				yy_push_state(TIMER);
				return token::TIMER_KEY;
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 170 "fsml.lex"
{
				log("found: SC\n");
				yy_pop_state();
				return token::SC;
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 176 "fsml.lex"
{
				log("found: VOID\n");
				return token::VOID;
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 181 "fsml.lex"
{
				log("found: CHAR\n");
				return token::CHAR;
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 186 "fsml.lex"
{
				log("found: SHORT\n");
				return token::SHORT;
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 191 "fsml.lex"
{
				log("found: INT\n");
				return token::INT;
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 196 "fsml.lex"
{
				log("found: LONG\n");
				return token::LONG;
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 201 "fsml.lex"
{
				log("found: FLOAT\n");
				return token::FLOAT;
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 206 "fsml.lex"
{
				log("found: DOUBLE\n");
				return token::DOUBLE;
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 211 "fsml.lex"
{
				log("found: SIGNED\n");
				return token::SIGNED;
			}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 216 "fsml.lex"
{
				log("found: UNSIGNED\n");
				return token::UNSIGNED;
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 221 "fsml.lex"
{
				log("found: UNION\n");
				return token::UNION;
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 226 "fsml.lex"
{
				log("found: STRUCT\n");
				return token::STRUCT;
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 231 "fsml.lex"
{
				log("found: ENUM\n");
				return token::ENUM;
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 236 "fsml.lex"
{
				log("found: INTEGER %s\n", FSMLtext);
				FSMLlval->emplace<int>(atoi(FSMLtext));
				return token::INTEGER_CONSTANT;
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 242 "fsml.lex"
{
				log("found: CHARACTER %s\n", FSMLtext);
				FSMLlval->emplace<std::string>(FSMLtext);
				return token::CHARACTER_CONSTANT;
			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 248 "fsml.lex"
{
				log("found: FLOAT %s\n", FSMLtext);
				FSMLlval->emplace<float>(atof(FSMLtext));
				return token::FLOATING_CONSTANT;
			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 254 "fsml.lex"
{
				log("found: UNTIL\n");
				yy_push_state(UNTIL);
				return token::UNTIL_KEY;
			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 262 "fsml.lex"
{
				log("found: STATE\n");
				yy_push_state(STATE);
				return token::STATE_KEY;
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 268 "fsml.lex"
{
				log("found: LSB\n");
				yy_push_state(STATE_TYPE);
				return token::LSB;
			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 274 "fsml.lex"
{
				log("found: RESET\n");
				return token::RESET;
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 279 "fsml.lex"
{
				log("found: END\n");
				return token::END;
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 284 "fsml.lex"
{
				log("found: ERR\n");
				return token::ERR;
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 289 "fsml.lex"
{
				log("found: RSB\n");
				yy_pop_state();
				return token::RSB;
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 295 "fsml.lex"
{
				log("Beginning C_CODE\n");
				tmp_str += std::string(FSMLtext);
				yy_push_state(C_CODE);
			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 301 "fsml.lex"
{
				log("found: ON\n");
				return token::ON;
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 306 "fsml.lex"
{
				log("Beginning C_CONDITION\n");
				tmp_str += std::string(FSMLtext);
				yy_push_state(C_CONDITION);
			}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 312 "fsml.lex"
{
				tmp_str += std::string(FSMLtext);
				b_cnt++;
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 317 "fsml.lex"
{
				tmp_str += std::string(FSMLtext);
				b_cnt--;
				if (b_cnt < 0) {
					log("found: C_CONDITION\n");
					b_cnt = 0;
					yy_pop_state();
					FSMLlval->emplace<std::string>(tmp_str); 
					tmp_str.clear();
					return token::C_CONDITION_BLOCK;
				}
			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 330 "fsml.lex"
{
				log("found: TIMEOUT\n");
				yy_push_state(TIMEOUT);
				return token::TIMEOUT_KEY;
			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 336 "fsml.lex"
{
				log("found RB\n");
				yy_pop_state();
				return token::RB;
			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 342 "fsml.lex"
{
				log("found: GO\n");
				return token::GO;
			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 347 "fsml.lex"
{
				log("found: RETRY\n");
				return token::RETRY;
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 352 "fsml.lex"
{
				log("found: OUT\n");
				return token::OUT;
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 357 "fsml.lex"
{
				log("found: START\n");
				return token::START;
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 362 "fsml.lex"
{
				log("found: SC\n");
				yy_pop_state();
				return token::SC;
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 368 "fsml.lex"
{ 
				log("found: IDENTIFIER %s\n", FSMLtext);
				FSMLlval->emplace<std::string>(FSMLtext);
				return token::IDENTIFIER;
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 374 "fsml.lex"
{
				log("found LCB\n");
				return token::LCB;
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 379 "fsml.lex"
{
				log("found RCB\n");
				return token::RCB;
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 384 "fsml.lex"
{
				log("found LB\n");
				return token::LB;
			}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 389 "fsml.lex"
{
				log("found RB\n");
				return token::RB;
			}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 394 "fsml.lex"
{
				log("found: COMMA\n");
				return token::COMMA;
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 399 "fsml.lex"
{
				log("found: EQUAL\n");
				return token::EQUAL;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 404 "fsml.lex"
{
				log("found: STAR\n");
				return token::STAR;
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 410 "fsml.lex"
{ tmp_str += std::string(FSMLtext); yy_push_state(C_COMMENT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 412 "fsml.lex"
{ tmp_str += std::string(FSMLtext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 413 "fsml.lex"
{ tmp_str += std::string(FSMLtext); }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 414 "fsml.lex"
{ ++line; yylloc->begin.line++; tmp_str += std::string(FSMLtext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 415 "fsml.lex"
{ tmp_str += std::string(FSMLtext); yy_pop_state(); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 417 "fsml.lex"
{ tmp_str += std::string(FSMLtext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 420 "fsml.lex"
{ tmp_str += std::string(FSMLtext); }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 421 "fsml.lex"
{ ++line; yylloc->begin.line++; tmp_str += std::string(FSMLtext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 425 "fsml.lex"
{ 
								yy_push_state(FSML_COMMENT); 
								log("removing comment\n"); 
							}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 429 "fsml.lex"

	YY_BREAK
case 67:
YY_RULE_SETUP
#line 430 "fsml.lex"

	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 431 "fsml.lex"
{ ++line; yylloc->begin.line++; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 432 "fsml.lex"
{ yy_pop_state(); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 433 "fsml.lex"
{ log("removing comment\n"); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DECL):
case YY_STATE_EOF(TIME):
case YY_STATE_EOF(PERIOD):
case YY_STATE_EOF(FSM):
case YY_STATE_EOF(VAR):
case YY_STATE_EOF(TIMER):
case YY_STATE_EOF(STATE):
case YY_STATE_EOF(STATE_TYPE):
case YY_STATE_EOF(TIMEOUT):
case YY_STATE_EOF(UNTIL):
case YY_STATE_EOF(C_CODE):
case YY_STATE_EOF(C_CONDITION):
case YY_STATE_EOF(C_COMMENT):
case YY_STATE_EOF(FSML_COMMENT):
#line 436 "fsml.lex"
{yyterminate();}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 438 "fsml.lex"
{ ++line; yylloc->begin.line++; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 440 "fsml.lex"
{ /* skip silently */ }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 441 "fsml.lex"
{ throw FSML::FSMLParser::syntax_error(*yylloc, "invalid character: " + std::string(FSMLtext)); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 443 "fsml.lex"
ECHO;
	YY_BREAK
#line 1564 "fsml.yy.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed FSMLin at a new source and called
			 * FSMLlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = FSMLin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( FSMLwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * FSMLtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of FSMLlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					FSMLrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			FSMLrestart(FSMLin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) FSMLrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 201 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 201 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 200);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					FSMLrestart(FSMLin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( FSMLwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve FSMLtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void FSMLrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        FSMLensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            FSML_create_buffer(FSMLin,YY_BUF_SIZE );
	}

	FSML_init_buffer(YY_CURRENT_BUFFER,input_file );
	FSML_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void FSML_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		FSMLpop_buffer_state();
	 *		FSMLpush_buffer_state(new_buffer);
     */
	FSMLensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	FSML_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (FSMLwrap()) processing, but the only time this flag
	 * is looked at is after FSMLwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void FSML_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	FSMLin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE FSML_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) FSMLalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in FSML_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) FSMLalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in FSML_create_buffer()" );

	b->yy_is_our_buffer = 1;

	FSML_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with FSML_create_buffer()
 * 
 */
    void FSML_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		FSMLfree((void *) b->yy_ch_buf  );

	FSMLfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a FSMLrestart() or at EOF.
 */
    static void FSML_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	FSML_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then FSML_init_buffer was _probably_
     * called from FSMLrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void FSML_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		FSML_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void FSMLpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	FSMLensure_buffer_stack();

	/* This block is copied from FSML_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from FSML_switch_to_buffer. */
	FSML_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void FSMLpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	FSML_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		FSML_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void FSMLensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)FSMLalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in FSMLensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)FSMLrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in FSMLensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE FSML_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) FSMLalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in FSML_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	FSML_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to FSMLlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       FSML_scan_bytes() instead.
 */
YY_BUFFER_STATE FSML_scan_string (yyconst char * yystr )
{
    
	return FSML_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to FSMLlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE FSML_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) FSMLalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in FSML_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = FSML_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in FSML_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) FSMLalloc(new_size  );

		else
			(yy_start_stack) = (int *) FSMLrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up FSMLtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		FSMLtext[FSMLleng] = (yy_hold_char); \
		(yy_c_buf_p) = FSMLtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		FSMLleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int FSMLget_lineno  (void)
{
        
    return FSMLlineno;
}

/** Get the input stream.
 * 
 */
FILE *FSMLget_in  (void)
{
        return FSMLin;
}

/** Get the output stream.
 * 
 */
FILE *FSMLget_out  (void)
{
        return FSMLout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t FSMLget_leng  (void)
{
        return FSMLleng;
}

/** Get the current token.
 * 
 */

char *FSMLget_text  (void)
{
        return FSMLtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void FSMLset_lineno (int  line_number )
{
    
    FSMLlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see FSML_switch_to_buffer
 */
void FSMLset_in (FILE *  in_str )
{
        FSMLin = in_str ;
}

void FSMLset_out (FILE *  out_str )
{
        FSMLout = out_str ;
}

int FSMLget_debug  (void)
{
        return FSML_flex_debug;
}

void FSMLset_debug (int  bdebug )
{
        FSML_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from FSMLlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    FSMLin = stdin;
    FSMLout = stdout;
#else
    FSMLin = (FILE *) 0;
    FSMLout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * FSMLlex_init()
     */
    return 0;
}

/* FSMLlex_destroy is for both reentrant and non-reentrant scanners. */
int FSMLlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		FSML_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		FSMLpop_buffer_state();
	}

	/* Destroy the stack itself. */
	FSMLfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        FSMLfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * FSMLlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *FSMLalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *FSMLrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void FSMLfree (void * ptr )
{
	free( (char *) ptr );	/* see FSMLrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 443 "fsml.lex"



#ifndef FSMLwrap
int FSMLwrap() 
{
	return 1;
}
#endif

void FSMLDriver::scanBegin()
{
	std::string msg; 
	if(!(FSMLin = fopen(filename_.c_str(), "r"))){
		msg += std::string("error opening ") + filename_ + std::string(": ") + strerror(errno);
		error(msg);
	}
}

void FSMLDriver::scanEnd()
{
	fclose(FSMLin);
	YY_FLUSH_BUFFER;
}


